---

name: QE Testing (Ubuntu-hosted)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  # Schedule a daily cron at midnight UTC
  schedule:
    - cron: '0 0 * * *'
env:
  TEST_REPO: redhat-best-practices-for-k8s/certsuite

jobs:
  qe-testing:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        suite: [accesscontrol, affiliatedcertification, manageability, networking, lifecycle, performance, platformalteration, observability, operator]
    env:
      SHELL: /bin/bash
      KUBECONFIG: '/home/runner/.kube/config'
      PFLT_DOCKERCONFIG: '/home/runner/.docker/config'
      TEST_CERTSUITE_IMAGE_NAME: quay.io/redhat-best-practices-for-k8s/certsuite
      TEST_CERTSUITE_IMAGE_TAG: unstable
      DOCKER_CONFIG_DIR: '/home/runner/.docker/'
      SKIP_PRELOAD_IMAGES: true # Not needed for github-hosted runs

    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: 1.23.4

      - name: Disable default go problem matcher
        run: echo "::remove-matcher owner=go::"

      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.sha }}

      - name: Set up test cluster with quick-k8s
        uses: palmsoftware/quick-k8s@v0.0.16
        with:
          numControlPlaneNodes: 1
          numWorkerNodes: 3
          installOLM: true
          removeDefaultStorageClass: true
          removeControlPlaneTaint: true

      - name: Clone the certsuite repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ env.TEST_REPO }}
          path: certsuite
          ref: main

      - name: Extract dependent Pull Requests
        uses: depends-on/depends-on-action@77e67971a155b35424508ada365790c47286fd0f # main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extra-dirs: certsuite-sample-workload certsuite

      - name: Run the tests (against image)
        uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3.0.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: FEATURES=${{matrix.suite}} CERTSUITE_REPO_PATH=${GITHUB_WORKSPACE}/certsuite CERTSUITE_IMAGE=${{env.TEST_CERTSUITE_IMAGE_NAME}} CERTSUITE_IMAGE_TAG=${{env.TEST_CERTSUITE_IMAGE_TAG}} DISABLE_INTRUSIVE_TESTS=true ENABLE_PARALLEL=true ENABLE_FLAKY_RETRY=true JOB_ID=${{github.run_id}} make test-features

      # Only run against the binary during a scheduled run
      - name: Build the binary
        run: make build-certsuite-tool
        working-directory: certsuite

      - name: Run the tests (against binary)
        uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3.0.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: FEATURES=${{matrix.suite}} CERTSUITE_REPO_PATH=${GITHUB_WORKSPACE}/certsuite USE_BINARY=true DISABLE_INTRUSIVE_TESTS=true ENABLE_PARALLEL=true ENABLE_FLAKY_RETRY=true JOB_ID=${{github.run_id}} make test-features

  check-all-dependencies-are-merged:
    runs-on: ubuntu-22.04
    steps:

      - name: Extract dependent PR
        uses: depends-on/depends-on-action@77e67971a155b35424508ada365790c47286fd0f # main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check-unmerged-pr: true

...
